openapi: 3.0.3
info:
  title: Indra Challenge
  description: |-
    Esta es la documentacion del API REST implementado como reto tecnico para solicitar el puesto de Backend Developer NodeJS
  contact:
    email: jerson.huaytac@gmail.com
  version: 1.0.11
externalDocs:
  description: Find out more about Swagger
  url: http://swagger.io
servers:
  - url: https://localhost:3000/dev
tags:
  - name: post
    description: Endpoints relacionados a la coleccion post
paths:
  /post/create:
    post:
      tags:
        - post
      summary: Agrega un nuevo post a la BD
      description: Agrega un nuevo post a la BD
      operationId: addPost
      requestBody:
        description: Crea un nuevo post
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/PostRequest'
        required: true
      responses:
        '200':
          description: Successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ApiCreatePostResponse'    
        '400':
          description: Bad Request
        '500':
          description: Internal server error
  /post:
    get:
      tags:
        - post
      summary: Retorna una lista de posts
      description: Retorna una lista de posts
      operationId: findPosts
      responses:
        '200':
          description: successful operation
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/ApiListPostResponse'
        '500':
          description: Internal server error
components:
  schemas:
    Post:
      type: object
      properties:
        id:
          type: string
          example: 1190daa3-25fb-49c0-ba2c-e734a0b576b4
        author:
          type: string
          example: Silvia Cammi
        review:
          type: string
          example: Ejemplo de calificacion
        title:
          type: string
          example: Ejemplo de titulo
        observation:
          type: string
          example: ejemplo de observacion
      xml:
        name: post
    PostRequest:
      type: object
      properties:
        author:
          type: string
          example: Silvia Cammi
        review:
          type: string
          example: Ejemplo de calificacion
        title:
          type: string
          example: Ejemplo de titulo
        observation:
          type: string
          example: ejemplo de observacion
      xml:
        name: post
    ApiCreatePostResponse:
      type: object
      properties:
        code:
          type: integer
          format: int32
          example: 0
        data:
          type: object
          properties:
            id:
              type: string
              example: 1190daa3-25fb-49c0-ba2c-e734a0b576b4
            autor:
              type: string
              example: Silvia Cammi
            calificacion:
              type: string
              example: Ejemplo de calificacion
            titulo:
              type: string
              example: Ejemplo de titulo
            observacion:
              type: string
              example: ejemplo de observacion
        message:
          type: string
          example: Created successfully
      xml:
        name: '##default'
    ApiListPostResponse:
      type: object
      properties:
        code:
          type: integer
          format: int32
          example: 0
        data:
          type: array
          items:
            type: object
            properties: 
              id:
                type: string
                example: 1190daa3-25fb-49c0-ba2c-e734a0b576b4
              autor:
                type: string
                example: Silvia Cammi
              calificacion:
                type: string
                example: Ejemplo de calificacion
              titulo:
                type: string
                example: Ejemplo de titulo
              observacion:
                type: string
                example: ejemplo de observacion
        message:
          type: string
          example: List of posts.
      xml:
        name: '##default'